### ISSUE TITLE
the paper of the NeuralNets-ImageCorrection

### ISSUE THREAD

**Issue by zhuzc123** [NeilDG/NeuralNets-ImageDepthExperiment#33]
Would you please provide some papers about the program of NeualNets-ImageCorrection,Thank you very much

**Comment by NeilDG** [comment]
> Would you please provide some papers about the program of NeualNets-ImageCorrection,Thank you very much

Hello. This is a relatively new study which was published just recently. See link here: https://www.mdpi.com/1424-8220/20/17/4898

We will provide more details on our Github repo soon.
