### ISSUE TITLE
Can the obtained Homography matrix be applied to other size of images

### ISSUE THREAD

**Issue by haochen23** [NeilDG/NeuralNets-ImageDepthExperiment#35]
Can you also provide inference code? Thanks in advance.

Can the obtained homography matrix be applied to other size of images?

**Comment by NeilDG** [comment]
Hello,

Regarding the homography matrix, supposed to be yes. However, we did not further test it on different resolutions. Our paper assumes a fixed size of distorted images.  Regarding inference code, we, unfortunately, don't have the time to add further documentation on this page as I'm currently doing a new project related to this as well.  The closest one you can refer to is the "warp_test_main.py"
